In [300]:
import pandas as pd
import numpy as np


In [301]:
df = pd.read_csv('Customer_Segmentation.csv')

In [302]:
df.head()

ID  Gender Ever_Married  Age Graduated     Profession  Work_Experience  \
0  462809    Male           No   22        No     Healthcare              1.0   
1  462643  Female          Yes   38       Yes       Engineer              NaN   
2  466315  Female          Yes   67       Yes       Engineer              1.0   
3  461735    Male          Yes   67       Yes         Lawyer              0.0   
4  462669  Female          Yes   40       Yes  Entertainment              NaN   

  Spending_Score  Family_Size  Var_1 Segmentation  
0            Low          4.0  Cat_4            D  
1        Average          3.0  Cat_4            A  
2            Low          1.0  Cat_6            B  
3           High          2.0  Cat_6            B  
4           High          6.0  Cat_6            A

In [303]:
from sklearn.model_selection import train_test_split

In [304]:
y = df.iloc[:,-1]
X = df.iloc[:,:-1]

In [305]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [306]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", y_test.shape)

Dimensi X_train :  (5647, 10)
Dimensi X_train :  (2421, 10)
Dimensi y_train :  (5647,)
Dimensi y_test :  (2421,)


In [307]:
from sklearn.preprocessing import MinMaxScaler

In [308]:
df2 = df[['Age', 'Work_Experience', 'Family_Size' ]]

In [309]:
df2.head()

Age  Work_Experience  Family_Size
0   22              1.0          4.0
1   38              NaN          3.0
2   67              1.0          1.0
3   67              0.0          2.0
4   40              NaN          6.0

In [310]:
ss = MinMaxScaler()

In [311]:
Scaled_data = ss.fit_transform(df2)

In [312]:
print("Nilai Data Sebelum scaling : ")
print(df2)
print("Nilai standar deviasi: \n", np.std(df2))

print("\n\n Nilai Data setelah scaling : ")
print(Scaled_data)
print("Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data Sebelum scaling : 
      Age  Work_Experience  Family_Size
0      22              1.0          4.0
1      38              NaN          3.0
2      67              1.0          1.0
3      67              0.0          2.0
4      40              NaN          6.0
...   ...              ...          ...
8063   22              0.0          7.0
8064   35              3.0          4.0
8065   33              1.0          1.0
8066   27              1.0          4.0
8067   37              0.0          3.0

[8068 rows x 3 columns]
Nilai standar deviasi: 
 Age                16.710661
Work_Experience     3.406528
Family_Size         1.531314
dtype: float64


 Nilai Data setelah scaling : 
[[0.05633803 0.07142857 0.375     ]
 [0.28169014        nan 0.25      ]
 [0.69014085 0.07142857 0.        ]
 ...
 [0.21126761 0.07142857 0.        ]
 [0.12676056 0.07142857 0.375     ]
 [0.26760563 0.         0.25      ]]
Nilai standar deviasi:  nan


In [313]:
from sklearn.preprocessing import StandardScaler

In [314]:
df3 = df[['Age', 'Work_Experience', 'Family_Size' ]]

In [315]:
df3.head()

Age  Work_Experience  Family_Size
0   22              1.0          4.0
1   38              NaN          3.0
2   67              1.0          1.0
3   67              0.0          2.0
4   40              NaN          6.0

In [316]:
ss = StandardScaler()
Scaled_data = ss.fit_transform(df3)

In [317]:
print("Nilai Data Sebelum scaling : ")
print(df3)
print("Nilai standar deviasi: \n", np.std(df3))

print("\n\n Nilai Data setelah scaling : ")
print(Scaled_data)
print("Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data Sebelum scaling : 
      Age  Work_Experience  Family_Size
0      22              1.0          4.0
1      38              NaN          3.0
2      67              1.0          1.0
3      67              0.0          2.0
4      40              NaN          6.0
...   ...              ...          ...
8063   22              0.0          7.0
8064   35              3.0          4.0
8065   33              1.0          1.0
8066   27              1.0          4.0
8067   37              0.0          3.0

[8068 rows x 3 columns]
Nilai standar deviasi: 
 Age                16.710661
Work_Experience     3.406528
Family_Size         1.531314
dtype: float64


 Nilai Data setelah scaling : 
[[-1.28462344 -0.48191689  0.75090867]
 [-0.32715082         nan  0.09787485]
 [ 1.40826831 -0.48191689 -1.20819279]
 ...
 [-0.62636101 -0.48191689 -1.20819279]
 [-0.98541324 -0.48191689  0.75090867]
 [-0.38699286 -0.77547094  0.09787485]]
Nilai standar deviasi:  nan


In [318]:
from sklearn.impute import SimpleImputer

In [319]:
df.isna().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [320]:
df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [321]:
imputer = SimpleImputer(strategy='most_frequent' )

In [322]:
df["Ever_Married"] = imputer.fit_transform(df[["Ever_Married"]])
df["Graduated"] = imputer.fit_transform(df[["Graduated"]])
df["Profession"] = imputer.fit_transform(df[["Profession"]])
df["Var_1"] = imputer.fit_transform(df[["Var_1"]])

In [323]:
df.isna().sum()

ID                   0
Gender               0
Ever_Married         0
Age                  0
Graduated            0
Profession           0
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1                0
Segmentation         0
dtype: int64

In [324]:
imputer2 = SimpleImputer(strategy='mean' )

In [325]:
df["Work_Experience"] = imputer.fit_transform(df[["Work_Experience"]])

In [326]:
df.isna().sum()

ID                   0
Gender               0
Ever_Married         0
Age                  0
Graduated            0
Profession           0
Work_Experience      0
Spending_Score       0
Family_Size        335
Var_1                0
Segmentation         0
dtype: int64

In [327]:
imputer3 = SimpleImputer(strategy='median' )

In [328]:
df["Family_Size"] = imputer.fit_transform(df[["Family_Size"]])

In [329]:
df.isna().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

In [330]:
print("Nilai Duplikat: ")
df[df.duplicated()]

Nilai Duplikat: 


Empty DataFrame
Columns: [ID, Gender, Ever_Married, Age, Graduated, Profession, Work_Experience, Spending_Score, Family_Size, Var_1, Segmentation]
Index: []

In [331]:
df.iloc[0]

ID                     462809
Gender                   Male
Ever_Married               No
Age                        22
Graduated                  No
Profession         Healthcare
Work_Experience           1.0
Spending_Score            Low
Family_Size               4.0
Var_1                   Cat_4
Segmentation                D
Name: 0, dtype: object

In [332]:
df = df.append(df.iloc[0:100])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17748\324845436.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df.iloc[0:100])


In [333]:
print("Nilai Duplikat: ")
df[df.duplicated()]

Nilai Duplikat: 


ID  Gender Ever_Married  Age Graduated     Profession  \
0   462809    Male           No   22        No     Healthcare   
1   462643  Female          Yes   38       Yes       Engineer   
2   466315  Female          Yes   67       Yes       Engineer   
3   461735    Male          Yes   67       Yes         Lawyer   
4   462669  Female          Yes   40       Yes  Entertainment   
..     ...     ...          ...  ...       ...            ...   
95  463845    Male          Yes   58       Yes         Artist   
96  459976  Female           No   38       Yes         Artist   
97  461334    Male          Yes   63       Yes         Artist   
98  465108    Male          Yes   58       Yes         Doctor   
99  462600    Male          Yes   30        No       Engineer   

    Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0               1.0            Low          4.0  Cat_4            D  
1               1.0        Average          3.0  Cat_4            A  
2               1.0            Low          1.0  Cat_6            B  
3               0.0           High          2.0  Cat_6            B  
4               1.0           High          6.0  Cat_6            A  
..              ...            ...          ...    ...          ...  
95              1.0        Average          1.0  Cat_6            D  
96              0.0            Low          1.0  Cat_6            D  
97              0.0           High          2.0  Cat_6            C  
98              1.0        Average          2.0  Cat_6            C  
99              3.0        Average          3.0  Cat_4            D  

[100 rows x 11 columns]

In [334]:
df.drop_duplicates(inplace=True)

In [335]:
print("Nilai Duplikat: ")
df[df.duplicated()]

Nilai Duplikat: 


Empty DataFrame
Columns: [ID, Gender, Ever_Married, Age, Graduated, Profession, Work_Experience, Spending_Score, Family_Size, Var_1, Segmentation]
Index: []

In [336]:
df['Age'] = df['Age'].astype('float64')

In [337]:
df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                float64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [338]:
from sklearn.preprocessing import OneHotEncoder

In [339]:
df.head()


ID  Gender Ever_Married   Age Graduated     Profession  \
0  462809    Male           No  22.0        No     Healthcare   
1  462643  Female          Yes  38.0       Yes       Engineer   
2  466315  Female          Yes  67.0       Yes       Engineer   
3  461735    Male          Yes  67.0       Yes         Lawyer   
4  462669  Female          Yes  40.0       Yes  Entertainment   

   Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0              1.0            Low          4.0  Cat_4            D  
1              1.0        Average          3.0  Cat_4            A  
2              1.0            Low          1.0  Cat_6            B  
3              0.0           High          2.0  Cat_6            B  
4              1.0           High          6.0  Cat_6            A

In [340]:
encoder = OneHotEncoder(sparse=False)
genderEnc = encoder.fit_transform(df[["Gender"]])

In [341]:
gender = pd.DataFrame(genderEnc)
df = df.join(gender)
df.head()

ID  Gender Ever_Married   Age Graduated     Profession  \
0  462809    Male           No  22.0        No     Healthcare   
1  462643  Female          Yes  38.0       Yes       Engineer   
2  466315  Female          Yes  67.0       Yes       Engineer   
3  461735    Male          Yes  67.0       Yes         Lawyer   
4  462669  Female          Yes  40.0       Yes  Entertainment   

   Work_Experience Spending_Score  Family_Size  Var_1 Segmentation    0    1  
0              1.0            Low          4.0  Cat_4            D  0.0  1.0  
1              1.0        Average          3.0  Cat_4            A  1.0  0.0  
2              1.0            Low          1.0  Cat_6            B  1.0  0.0  
3              0.0           High          2.0  Cat_6            B  0.0  1.0  
4              1.0           High          6.0  Cat_6            A  1.0  0.0

In [342]:
df = df.rename(columns={
    0 : 'Female',
    1 : 'Male'
})

In [343]:
encoder = OneHotEncoder(sparse=False)
GraduatedEnc = encoder.fit_transform(df[["Graduated"]])

In [344]:
GraduatedEnc = pd.DataFrame(GraduatedEnc)
df = df.join(GraduatedEnc)
df.head()

ID  Gender Ever_Married   Age Graduated     Profession  \
0  462809    Male           No  22.0        No     Healthcare   
1  462643  Female          Yes  38.0       Yes       Engineer   
2  466315  Female          Yes  67.0       Yes       Engineer   
3  461735    Male          Yes  67.0       Yes         Lawyer   
4  462669  Female          Yes  40.0       Yes  Entertainment   

   Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  Female  \
0              1.0            Low          4.0  Cat_4            D     0.0   
1              1.0        Average          3.0  Cat_4            A     1.0   
2              1.0            Low          1.0  Cat_6            B     1.0   
3              0.0           High          2.0  Cat_6            B     0.0   
4              1.0           High          6.0  Cat_6            A     1.0   

   Male    0    1  
0   1.0  1.0  0.0  
1   0.0  0.0  1.0  
2   0.0  0.0  1.0  
3   1.0  0.0  1.0  
4   0.0  0.0  1.0

In [345]:
df = df.rename(columns={
    0 : 'Graduated_No ',
    1 : 'Graduated_Yes'
})

In [346]:
df.head()

ID  Gender Ever_Married   Age Graduated     Profession  \
0  462809    Male           No  22.0        No     Healthcare   
1  462643  Female          Yes  38.0       Yes       Engineer   
2  466315  Female          Yes  67.0       Yes       Engineer   
3  461735    Male          Yes  67.0       Yes         Lawyer   
4  462669  Female          Yes  40.0       Yes  Entertainment   

   Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  Female  \
0              1.0            Low          4.0  Cat_4            D     0.0   
1              1.0        Average          3.0  Cat_4            A     1.0   
2              1.0            Low          1.0  Cat_6            B     1.0   
3              0.0           High          2.0  Cat_6            B     0.0   
4              1.0           High          6.0  Cat_6            A     1.0   

   Male  Graduated_No   Graduated_Yes  
0   1.0            1.0            0.0  
1   0.0            0.0            1.0  
2   0.0            0.0            1.0  
3   1.0            0.0            1.0  
4   0.0            0.0            1.0